import React from 'react';

const Table = () => {
    return (
        <>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Details</th>
                    <th>Year</th>
                </tr>
                <tr>
                    <td className='link'>
                        <a href='https://github.com/danielkluzner/paxos-blockchain'>Paxos Blockchain</a>
                    </td>
                    <td>
                        Using python, built a simplified blockchain using Paxos as a consensus protocol in the
                        Distributed Systems course. The blockchain could tolerate both link and process failures,
                        and maintained a queue for pending transactions. The network consisted of 5 processes
                        that spawned multiple threads, and used sockets and message-passing for
                        communication.
                    </td>
                    <td>2020</td>
                </tr>
                <tr>
                    <td className='link'>
                        <a href='https://www.youtube.com/watch?v=Y6lSfG6yC_k'>Dampened Cloth Simulation</a>
                    </td>
                    <td>
                        Using C++ and a mass-spring model, a Computer Graphics project simulated the movement
                        of a dampened cloth being let go at two corners and left to dangle. The positions of the
                        masses were updated using the Implicit Euler method along with conjugate gradient
                        descent. The program output “obj” files containing the positions of the masses at each
                        frame. These files were fed into Houdini, a 3D animation software application, in order
                        to render usable images that could then be used in a sequence to create a smooth
                        animation of the cloth.
                    </td>
                    <td>2020</td>
                </tr>
                <tr>
                    <td className='link'>
                        <a href='https://sites.google.com/view/quadcopter-ece-153b-w2020'>Remote-Controlled Drone</a>
                    </td>
                    <td>
                        During the final project of Sensor and Peripheral Interface Design, applied concepts of
                        pulse width modulation (PWM) and communication protocols (SPI and IC2) in order to build
                        a functioning remote-controlled quadcopter. The project centered around using microcontrollers ile
                        interfacing with peripheral devices such as the motors, a voltage sensor, and transceivers that
                        communicated between each other to mimic the “remote control.” Programs downloaded onto the
                        microcontrollers were written in C.
                    </td>
                    <td>2020</td>
                </tr>
                <tr>
                    <td className='link'>
                        <a href='https://github.com/danielkluzner/tennis-match-predicting'>Predicting Tennis Matches</a>
                    </td>
                    <td>
                        A project in the Optimization Theory course was completed using Matlab, and involved formulation of a
                        convex optimization problem. The project aimed to train a model with the purpose of predicting the
                        outcome of a hypothetical tennis match between two professional tennis players. The model was trained
                        using data from previous tournaments and matches— specifically the odds generated by several gambling
                        companies— and relied on logistic regression and batch gradient descent. The model had a 65% accuracy,
                        which is reasonably impressive seeing how tennis betting is plain gambling.
                    </td>
                    <td>2020</td>
                </tr>
            </table>
        </>
    );
}

export default Table;